// <auto-generated />
using System;
using BikeRentalApplication.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BikeRentalApplication.Migrations
{
    [DbContext(typeof(RentalDbContext))]
    partial class RentalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BikeRentalApplication.Entities.Bike", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("RatePerHour")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Bikes");
                });

            modelBuilder.Entity("BikeRentalApplication.Entities.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BikeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BikeId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("BikeRentalApplication.Entities.InventoryUnit", b =>
                {
                    b.Property<string>("RegistrationNo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Availability")
                        .HasColumnType("bit");

                    b.Property<Guid>("BikeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("YearOfManufacture")
                        .HasColumnType("int");

                    b.HasKey("RegistrationNo");

                    b.HasIndex("BikeId");

                    b.ToTable("InventoryUnits");
                });

            modelBuilder.Entity("BikeRentalApplication.Entities.RentalRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BikeRegNo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("Payment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("RentalOut")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RentalRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("RentalReturn")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserNICNumber")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("BikeRegNo");

                    b.HasIndex("RentalRequestId")
                        .IsUnique();

                    b.HasIndex("UserNICNumber");

                    b.ToTable("RentalRecords");
                });

            modelBuilder.Entity("BikeRentalApplication.Entities.RentalRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BikeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NICNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool?>("Notify")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RequestTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BikeId");

                    b.HasIndex("NICNumber");

                    b.ToTable("RentalRequests");
                });

            modelBuilder.Entity("BikeRentalApplication.Entities.User", b =>
                {
                    b.Property<string>("NICNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("AccountCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NICNumber");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BikeRentalApplication.Entities.Image", b =>
                {
                    b.HasOne("BikeRentalApplication.Entities.Bike", "Bike")
                        .WithMany("Images")
                        .HasForeignKey("BikeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bike");
                });

            modelBuilder.Entity("BikeRentalApplication.Entities.InventoryUnit", b =>
                {
                    b.HasOne("BikeRentalApplication.Entities.Bike", "Bike")
                        .WithMany("InventoryUnits")
                        .HasForeignKey("BikeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bike");
                });

            modelBuilder.Entity("BikeRentalApplication.Entities.RentalRecord", b =>
                {
                    b.HasOne("BikeRentalApplication.Entities.InventoryUnit", "InventoryUnit")
                        .WithMany("RentalRecords")
                        .HasForeignKey("BikeRegNo");

                    b.HasOne("BikeRentalApplication.Entities.RentalRequest", "RentalRequest")
                        .WithOne("RentalRecord")
                        .HasForeignKey("BikeRentalApplication.Entities.RentalRecord", "RentalRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BikeRentalApplication.Entities.User", null)
                        .WithMany("RentalRecords")
                        .HasForeignKey("UserNICNumber");

                    b.Navigation("InventoryUnit");

                    b.Navigation("RentalRequest");
                });

            modelBuilder.Entity("BikeRentalApplication.Entities.RentalRequest", b =>
                {
                    b.HasOne("BikeRentalApplication.Entities.Bike", "Bike")
                        .WithMany("RentalRequests")
                        .HasForeignKey("BikeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BikeRentalApplication.Entities.User", "User")
                        .WithMany("RentalRequests")
                        .HasForeignKey("NICNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bike");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BikeRentalApplication.Entities.Bike", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("InventoryUnits");

                    b.Navigation("RentalRequests");
                });

            modelBuilder.Entity("BikeRentalApplication.Entities.InventoryUnit", b =>
                {
                    b.Navigation("RentalRecords");
                });

            modelBuilder.Entity("BikeRentalApplication.Entities.RentalRequest", b =>
                {
                    b.Navigation("RentalRecord");
                });

            modelBuilder.Entity("BikeRentalApplication.Entities.User", b =>
                {
                    b.Navigation("RentalRecords");

                    b.Navigation("RentalRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
